[2024-12-13T08:31:46.326+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-12-13T08:31:42.646165+00:00 [queued]>
[2024-12-13T08:31:46.330+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-12-13T08:31:42.646165+00:00 [queued]>
[2024-12-13T08:31:46.330+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2024-12-13T08:31:46.339+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-12-13 08:31:42.646165+00:00
[2024-12-13T08:31:46.341+0000] {standard_task_runner.py:57} INFO - Started process 10698 to run task
[2024-12-13T08:31:46.344+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2024-12-13T08:31:42.646165+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmp1zvze54k']
[2024-12-13T08:31:46.345+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask extract_task
[2024-12-13T08:31:46.368+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_dag.extract_task manual__2024-12-13T08:31:42.646165+00:00 [running]> on host codespaces-586565
[2024-12-13T08:31:46.416+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T08:31:42.646165+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T08:31:42.646165+00:00'
[2024-12-13T08:31:46.417+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-13T08:31:46.417+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -O /workspace/lab/orchestrated/airflow-extract-data.csv https://lnkd.in/gfENQi7K']
[2024-12-13T08:31:46.422+0000] {subprocess.py:86} INFO - Output:
[2024-12-13T08:31:46.425+0000] {subprocess.py:93} INFO - /workspace/lab/orchestrated/airflow-extract-data.csv: No such file or directory
[2024-12-13T08:31:46.426+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-13T08:31:46.430+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-13T08:31:46.432+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_dag, task_id=extract_task, execution_date=20241213T083142, start_date=20241213T083146, end_date=20241213T083146
[2024-12-13T08:31:46.439+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task extract_task (Bash command failed. The command returned a non-zero exit code 1.; 10698)
[2024-12-13T08:31:46.475+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T08:31:46.483+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
